# Generated by Django 5.0 on 2024-02-18 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flip_detection", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flipdetection",
            old_name="user",
            new_name="user_id",
        ),
    ]
